### ISSUE TITLE
地図のセンター位置

### ISSUE THREAD

**Issue by HiroAsa** [codeformatsudo/MatsudoHornet#2]
スマホだと左下のインジケーターが結構でかいのでインジケーターを小さくするか地図のセンターを少し下げてはどうでしょうか

**Comment by egurin** [comment]
スマホの場合に・・・というロジックを組み込むのが私では難しいです
ドラッグによるパン操作を可とし、PC閲覧を推奨する旨、表示しました。

**Comment by egurin** [comment]
出来そうな気がしているのでちょっとやってみます

**Comment by egurin** [comment]
スマホの場合は地図のセンターを上本郷あたりにしました。
後はドラッグによるパン操作で見ていただくという事で(^^;
