### ISSUE TITLE
iPoneだけ？Maxボタンで地図が消える

### ISSUE THREAD

**Issue by HiroAsa** [codeformatsudo/MatsudoHornet#4]
地図のMaxボタン押下で地図画像が消えてしまう

**Comment by egurin** [comment]
私のiPhoneも同様です。PCでの閲覧を推奨する旨、メッセージ表示しました。

**Comment by egurin** [comment]
モバイルの場合はMaxボタンを非表示にしました。PC、タブレットではボタン表示されます。
※iPhoneでは非表示、iPadでは表示、PCでは表示される事を確認
